# Generated by Django 4.0.3 on 2022-08-27 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclass', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclass.class')),
                ('vote_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recruitpost',
            name='vote',
            field=models.ManyToManyField(to='recruit.vote'),
        ),
    ]
